name: unr1dacted
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - accelerate
  - pytorch
  - sentencepiece
  - transformers
  - pyarrow
  - pip:
    - "datasets>=2.18.0"
    - "openai>=1.0.0"
    - "python-dotenv>=1.0.0"
    - "streamlit>=1.35.0"
    - "matplotlib>=3.8.0"
